{
 "title": "Python Frontend/Backend Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} |= `Frontend` or `Backend`"
    }
   ]
  },
  {
   "title": "Metrics for request duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alice_request_duration_seconds)",
     "legendFormat": "Frontend request duration"
    },
    {
     "expr": "avg(cheshire_request_duration_seconds)",
     "legendFormat": "Backend request duration"
    }
   ]
  },
  {
   "title": "Metrics for total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "alice_requests_total", "legendFormat": "Frontend requests total" },
    { "expr": "cheshire_requests_total", "legendFormat": "Backend requests total" }
   ]
  },
  {
   "title": "Request latency seconds bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(alice_request_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "Frontend request latency seconds bucket (le 5.0)"
    },
    {
     "expr": "sum by(instance) (rate(cheshire_request_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "Backend request latency seconds bucket (le 5.0)"
    }
   ]
  }
 ]
}