name: Check markdown quality via Linter

env:
  KPA_PROJECT: kiratech

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mmul-it/kpa:v1.0.0
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create symlink to workspace
        run: ln -sf /__w/labs/labs /kpa/projects/${KPA_PROJECT}
      - name: Check markdown files for example project
        run: mdl -c /kpa/.mdlrc $(find /kpa/projects/${KPA_PROJECT}/ -name '*.md')
